import type { Metadata } from "next";
import { DM_Sans, Figtree } from "next/font/google";
import "../styles/globals.css";

import NextTopLoader from "nextjs-toploader";

const figTree = Figtree({ subsets: ["latin"], variable: "--figTree" });
const dm_sans = DM_Sans({ subsets: ["latin"], variable: "--dm-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${figTree.variable} ${dm_sans.variable}`}
      >
        <NextTopLoader color="#ADFF1C" />
        {children}
      </body>
    </html>
  );
}
